spring:
  boot:
    admin:
      client:
        url: http://localhost:8084
  application:
    name: Proposta
jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      format_sql: false
  database-platform: org.hibernate.dialect.H2Dialect
h2:
  console:
    enabled: true
    path: /h2-console
datasource:
  driver-class-name: org.h2.Driver
  url: jdbc:h2:file:C:/data/testedb
  username: sa
  password:
server:
  port: 8081
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: metrics,health,info
  metrics:
    enable:
      executor: false
  endpoint:
    metrics:
      enabled: true
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
info:
  application:
    nome: API de MS-Proposta
    descricao: API para gerenciamento de proposta