spring:
  application:
    name: resultado
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: false

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:C:/data/testedb
    username: sa
    password:

server:
  port: 8083

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: metrics,health,info
  metrics:
    enable:
      executor: false
  endpoint:
    metrics:
      enabled: true
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true

info:
  application:
    nome: API de MS-Resultado
    descricao: API para gerenciamento de resultado
